name: Update packages
on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iomorphic/image/cicd-py:0.0.3
      volumes:
        - /usr/bin/docker:/usr/bin/docker
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: '2'
    - name: Update
      run: just update
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: Update packages version to match upstream
        title: 'Packages Update: ${{ steps.date.outputs.date }}'
        branch: 'update-${{ github.run_id }}'
